apiVersion: v1
kind: Endpoints
metadata:
  name: camshare-svc
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.88.133
    ports:
    - port: 1935
      name: rtmp
      protocol: TCP
  - addresses:
    - ip: 192.168.88.133
    ports:
    - port: 9200
      name: http
      protocol: TCP    
---

apiVersion: v1
kind: Service
metadata:
  name: camshare-svc
spec:
  ports:
  - port: 1935
    name: rtmp
    protocol: TCP
  - port: 9200
    name: http
    protocol: TCP
---