apiVersion: v1
kind: Pod
metadata:
  name: mediaserver-pod
spec:
  containers:
  - name: mediaserver
    image: 192.168.88.133:5000/mediaserver:latest
    ports:
    - name: ice
      containerPort: 3478
      protocol: TCP
    - name: ice-udp
      containerPort: 3478
      protocol: UDP
    - name: ws
      containerPort: 9981
      protocol: TCP
    volumeMounts:
    - mountPath: /app/live/mediaserver/log
      name: hostlog
    command: ["/app/live/mediaserver/script/docker_init.sh"]
    args: []
  volumes:
  - name: hostlog
    hostPath:
      path: /tmp/mediaserver/log/    
  restartPolicy: Always