apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-svc
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.8.177
    ports:
    - port: 3306
      name: mysql
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
