apiVersion: v1
kind: Endpoints
metadata:
  name: rtmp-svc
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.88.133
    ports:
    - port: 4000
      name: rtmp
      protocol: TCP
  - addresses:
    - ip: 192.168.88.133
    ports:
    - port: 8899
      name: rtmp-8899
      protocol: TCP    

---
apiVersion: v1
kind: Service
metadata:
  name: rtmp-svc
spec:
  ports:
  - port: 4000
    name: rtmp
    protocol: TCP
  - port: 8899
    name: rtmp-8899
    protocol: TCP
